#服务器配置
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
#  servlet:
#    context-path: /

#模板配置
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  mvc:
      static-path-pattern: /**    #静态文件请求匹配方式
  resources:
    static-locations: classpath:/templates/,classpath:/static/,classpath:/config/    #设置静态资源访问路径

  #redis配置
  redis:
    host: 192.168.0.20  #redis服务器地址
    port: 6379          #redis服务器端口
    database: 0         #数据库索引（默认为0）
    password: 123456    #服务器密码（默认为空）
    timeout: 100        #连接超时时间（毫秒）
    jedis:              #jedis连接池
      pool:
        max-active: 8   #最大连接数
        max-wait: -1    #最大阻塞等待时间（负值表示没有限制）
        max-idle: 8     #最大空闲连接
        min-idle: 0     #最小空闲连接
#    cluster:            #集群配置
#      nodes: 192.168.0.20:6379,192.168.0.29:6037
#      max-redirects: 3




#数据源配置
  datasource:
    #Druid配置
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      #JDBC数据库设置
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root

      #连接池的配置
      initial-size: 5    #初始连接数
      min-idle: 1        #最小连接数
      max-active: 50     #最大连接数
      max-wait: 60000    #获取链接等待超时的时间
      time-between-eviction-runs-millis: 60000    #间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000      #配置一个连接在池中最小生存的时间，单位是毫秒
      # 校验SQL，Oracle配置 spring.datasource.validationQuery=SELECT 1 FROM DUAL，如果不配validationQuery项，则下面三项配置无用
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true   # 打开PSCache，并且指定每个连接上PSCache的大小
      max-pool-prepared-statement-per-connection-size: 20
      log-abandoned: true
#      filters:        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j2
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true   # 合并多个DruidDataSource的监控数据





######监控配置######
      #WebStatFilter配置
#      web-stat-filter:
#        enable: true
#        url-pattern: /*
#        exclusions: *.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*
#        session-stat-enable: true
#        session-stat-max-count:
#        principal-session-name:
#        principal-cookie-name:
#        profile-enable:

      #StatViewServlet配置
#      stat-view-servlet:
#        enable: true
#        url-pattern:
#        reset-enable: false
#        login-username: admin
#        login-password: 123456
#        allow:  127.0.0.1
#        deny: 192.168.1.73

      #Spring监控配置,配置_Druid和Spring关联监控配置
#      aop-patterns:             # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#日志配置
logging:
  config: classpath:config/log4j2.yml   #引入日志管理的log4j2的配置文件


