#服务器配置
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
#  servlet:
#    context-path: /

#模板配置
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  mvc:
      static-path-pattern: /**    #静态文件请求匹配方式
  resources:
    static-locations: classpath:/templates/,classpath:/static/    #设置静态资源访问路径

#数据源配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true







